# Generated by Django 5.1.2 on 2024-11-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='name_clinic',
            field=models.TextField(max_length=30, verbose_name='Название клиники'),
        ),
    ]
