# Generated by Django 5.1.2 on 2024-11-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics_app', '0004_alter_clinic_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='cite',
            field=models.CharField(default=2, max_length=100, verbose_name='Сайт'),
            preserve_default=False,
        ),
    ]
