# Generated by Django 5.1.2 on 2024-11-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics_app', '0005_clinic_cite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='adress',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='cite',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='city',
            field=models.CharField(max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='name_clinic',
            field=models.TextField(max_length=100, verbose_name='Название клиники'),
        ),
    ]
