# Generated by Django 5.1.2 on 2024-11-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics_app', '0007_alter_clinic_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='cite',
            field=models.URLField(blank=True, default=2, verbose_name='Сайт'),
            preserve_default=False,
        ),
    ]
