# Generated by Django 5.1.2 on 2024-11-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics_app', '0008_alter_clinic_cite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='cite',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт'),
        ),
    ]
