# Generated by Django 5.1.2 on 2024-11-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics_app', '0009_alter_clinic_cite'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='logo',
            field=models.ImageField(default=2, upload_to='logos/'),
            preserve_default=False,
        ),
    ]
