# Generated by Django 5.1.2 on 2024-11-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics_app', '0010_clinic_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='map_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на клинику'),
        ),
        migrations.AlterField(
            model_name='clinic',
            name='logo',
            field=models.ImageField(upload_to='logos/', verbose_name='Лого'),
        ),
    ]
