# Generated by Django 5.1.2 on 2024-11-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics_app', '0011_clinic_map_link_alter_clinic_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='map_link',
            field=models.URLField(blank=True, max_length=1500, null=True, verbose_name='Ссылка на клинику'),
        ),
    ]
