# Generated by Django 5.1.2 on 2024-11-25 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics_app', '0012_alter_clinic_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='map_link',
            field=models.TextField(blank=True, max_length=1500, null=True, verbose_name='Ссылка на клинику'),
        ),
    ]
