# Generated by Django 5.1.2 on 2024-11-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics_app', '0013_alter_clinic_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Лого'),
        ),
    ]
