# Generated by Django 5.1.2 on 2024-11-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics_app', '0014_alter_clinic_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='logo',
            field=models.ImageField(default=2, upload_to='logos/', verbose_name='Лого'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinic',
            name='map_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на клинику'),
        ),
    ]
