# Generated by Django 5.1.2 on 2024-11-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='link',
            field=models.URLField(verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name_group',
            field=models.CharField(max_length=100, verbose_name='Название группы'),
        ),
    ]
