# Generated by Django 5.1.2 on 2024-11-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0002_alter_group_link_alter_group_name_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='link',
        ),
        migrations.AddField(
            model_name='group',
            name='link_cite',
            field=models.URLField(default=2, verbose_name='Ссылка на сайт (если есть)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='link_vk',
            field=models.URLField(default=2, verbose_name='Ссылка в VK'),
            preserve_default=False,
        ),
    ]
