# Generated by Django 5.1.2 on 2024-11-23 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0003_remove_group_link_group_link_cite_group_link_vk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='link_cite',
            field=models.CharField(verbose_name='Ссылка на сайт (если есть)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='link_vk',
            field=models.CharField(verbose_name='Ссылка в VK'),
        ),
    ]
