# Generated by Django 5.1.2 on 2024-11-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0004_alter_group_link_cite_alter_group_link_vk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='link_cite',
            field=models.CharField(blank=True, null=True, verbose_name='Ссылка на сайт (если есть)'),
        ),
    ]
