# Generated by Django 5.1.2 on 2024-11-24 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0005_alter_group_link_cite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='link_cite',
        ),
    ]
