# Generated by Django 5.1.2 on 2024-11-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups_app', '0006_remove_group_link_cite'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cite',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт'),
        ),
    ]
