# Generated by Django 5.1.2 on 2024-11-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Цель объявления')),
            ],
            options={
                'verbose_name': 'Цель для нового дома',
                'verbose_name_plural': 'Цели для нового дома',
            },
        ),
        migrations.CreateModel(
            name='Kind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Вид животного')),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Виды',
            },
        ),
        migrations.CreateModel(
            name='Animal_house',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=500, verbose_name='Описание')),
                ('city', models.TextField(max_length=30, verbose_name='Город')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('contact_people', models.CharField(max_length=100, verbose_name='Контактное лицо')),
                ('house', models.ManyToManyField(to='house_app.house', verbose_name='Цель объявления')),
                ('kind', models.ManyToManyField(to='house_app.kind', verbose_name='Вид животного')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
