# Generated by Django 5.1.2 on 2024-11-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animal_house',
            new_name='Animal',
        ),
    ]
