# Generated by Django 5.1.2 on 2024-10-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='nickname',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='animal',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
