# Generated by Django 5.1.2 on 2024-10-31 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0003_kind_alter_animal_create_at_alter_animal_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kind',
            options={'verbose_name': 'Вид', 'verbose_name_plural': 'Виды'},
        ),
    ]
