# Generated by Django 5.1.2 on 2024-11-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0004_alter_kind_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Заголовок', 'verbose_name_plural': 'Заголовки'},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='kind',
        ),
        migrations.AddField(
            model_name='animal',
            name='kind',
            field=models.ManyToManyField(to='animals_app.kind', verbose_name='Виды'),
        ),
    ]
