# Generated by Django 5.1.2 on 2024-11-04 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0007_animal_quantity_animal_submit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='quantity',
        ),
    ]
