# Generated by Django 5.1.2 on 2024-11-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0008_remove_animal_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='kind',
            field=models.ManyToManyField(to='animals_app.kind', verbose_name='Вид животного'),
        ),
        migrations.AlterField(
            model_name='kind',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Вид животного'),
        ),
    ]
