# Generated by Django 5.1.2 on 2024-11-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0009_alter_animal_kind_alter_kind_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Проверено администратором?'),
        ),
    ]
