# Generated by Django 5.1.2 on 2024-11-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0010_animal_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='animals/', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Виды',
            },
        ),
        migrations.AlterModelOptions(
            name='kind',
            options={},
        ),
    ]
