# Generated by Django 5.1.2 on 2024-11-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0012_delete_image_alter_kind_options_alter_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animals/', verbose_name='Фото'),
        ),
    ]
