# Generated by Django 5.1.2 on 2024-11-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0015_alter_kind_options_alter_postimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фото'},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='title',
        ),
        migrations.AddField(
            model_name='animal',
            name='target',
            field=models.CharField(default=2, max_length=100, verbose_name='Цель объявления'),
            preserve_default=False,
        ),
    ]
