# Generated by Django 5.1.2 on 2024-11-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0016_alter_postimage_options_remove_animal_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Цель объявления')),
            ],
            options={
                'verbose_name': 'Вид',
                'verbose_name_plural': 'Виды',
            },
        ),
        migrations.AlterModelOptions(
            name='animal',
            options={},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='target',
        ),
        migrations.AddField(
            model_name='animal',
            name='target',
            field=models.ManyToManyField(to='animals_app.target', verbose_name='Цель объявления'),
        ),
    ]
