# Generated by Django 5.1.2 on 2024-11-07 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0017_target_alter_animal_options_remove_animal_target_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'verbose_name': 'Цель', 'verbose_name_plural': 'Цели'},
        ),
    ]
