# Generated by Django 5.1.2 on 2024-11-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0018_alter_target_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.RenameField(
            model_name='kind',
            old_name='name',
            new_name='name_1',
        ),
    ]
