# Generated by Django 5.1.2 on 2024-11-07 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0019_alter_animal_options_rename_name_kind_name_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kind',
            old_name='name_1',
            new_name='kind',
        ),
    ]
