# Generated by Django 5.1.2 on 2024-11-07 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0020_rename_name_1_kind_kind'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kind',
            old_name='kind',
            new_name='name',
        ),
    ]
