# Generated by Django 5.1.2 on 2024-11-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0021_rename_kind_kind_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='city',
            field=models.TextField(default=2, max_length=100, verbose_name='Город'),
            preserve_default=False,
        ),
    ]
