# Generated by Django 5.1.2 on 2024-11-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0022_animal_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='city',
            field=models.TextField(max_length=30, verbose_name='Город'),
        ),
    ]
