# Generated by Django 5.1.2 on 2024-11-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0023_alter_animal_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='contact_people',
            field=models.CharField(default=2, max_length=100, verbose_name='Контактное лицо'),
            preserve_default=False,
        ),
    ]
