# Generated by Django 5.1.2 on 2024-11-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0024_animal_contact_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Цель объявления')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
            },
        ),
        migrations.AddField(
            model_name='animal',
            name='house',
            field=models.ManyToManyField(to='animals_app.house', verbose_name='Цель объявления'),
        ),
    ]
