# Generated by Django 5.1.2 on 2024-11-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0025_house_animal_house'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': 'Цель для нового дома', 'verbose_name_plural': 'Цели для нового дома'},
        ),
        migrations.RemoveField(
            model_name='animal',
            name='house',
        ),
        migrations.AddField(
            model_name='animal',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество животных'),
        ),
    ]
