# Generated by Django 5.1.2 on 2024-11-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0026_alter_house_options_remove_animal_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество животных'),
        ),
    ]
