# Generated by Django 5.1.2 on 2024-11-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0027_alter_animal_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='images',
        ),
        migrations.AddField(
            model_name='postimage',
            name='pic',
            field=models.FileField(default=2, upload_to='animals/'),
            preserve_default=False,
        ),
    ]
