# Generated by Django 5.1.2 on 2024-11-10 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0028_remove_postimage_image_remove_postimage_images_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImage',
            new_name='Image',
        ),
    ]
