# Generated by Django 5.1.2 on 2024-11-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0029_rename_postimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='animals/', verbose_name='Фото')),
                ('images', models.ImageField(upload_to='animals/')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
