# Generated by Django 5.1.2 on 2024-11-13 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0031_delete_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='quantity',
        ),
    ]
