# Generated by Django 5.1.2 on 2024-11-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals_app', '0032_remove_animal_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество животных'),
        ),
    ]
